M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Tue 05 Mar 2024 04:26:21 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-05T16:26:21-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.487Y-3.837
X4.537Y-1.937
X6.537Y-2.537
X6.537Y-3.637
M30
